### ISSUE TITLE
"Add Descope Middleware after the SessionMiddleware"

### ISSUE THREAD

**Issue by benjamin-kirkbride** [descope/django-descope#147]
I haven't tested this exhaustively, but it seems like this is somewhat misleading. The Descope Middleware needs to go after a bunch of things, not just the SessionMiddleware. I would suggest stating that it should go at the end, as the errors you get is far from obvious that that's the problem.

**Comment by guyp-descope** [comment]
Thanks for the feedback @benjamin-kirkbride, we will improve this doc.

**Comment by omercnet** [comment]
`DescopeMiddleware` will try to validate the session provided from the user on every request
it must be able to access existing session information which is why the `SessionMiddleware` has to be added BEFORE `DescopeMiddleware`
The session validation uses the [Descope Python SDK](https://github.com/descope/python-sdk/) so it doesn't need any other Django middleware

this is why it must come only after the `SessionMiddleware`

Could you elaborate on any issues you encountered that were solved by moving `DescopeMiddleware` after any other middleware ?

**Comment by omercnet** [comment]
Did some more digging and realized AuthenticationMiddleware is also required as we use the `login` method, #150 will fix the docs to highlight it

thanks for the reprot!
